owner: mskz-ptplus-jp
repo: pauth.me-upptime

sites:
  - name: pauth.me
    url: https://pauth.me
  - name: pauth.me API
    url: https://pauth.me/api/v1/
    method: GET
  - name: demo.pauth.me
    url: https://demo.pauth.me

status-website:
  cname: status.pauth.me
  name: pauth.me Status
  introTitle: "**pauth.me** サービス稼働状況"
  introMessage: "着信認証API pauth.me のリアルタイム稼働状況です。障害発生時はこのページで最新情報をお知らせします。"
  navbar:
    - title: Status
      href: /
    - title: pauth.me
      href: https://pauth.me
