owner: mskz-ptplus-jp
repo: pauth.me-upptime

sites:
  - name: pauth.me
    url: https://pauth.me
  - name: API
    url: https://pauth.me/api/v1/health
  - name: Demo
    url: https://demo.pauth.me

status-website:
  cname: status.pauth.me
  logoUrl: https://pauth.me/favicon.ico
  name: pauth.me Status
  introTitle: "**pauth.me** サービス稼働状況"
  introMessage: "[pauth.me](https://pauth.me) の着信認証APIおよび関連サービスのリアルタイム稼働状況です。監視は [Upptime](https://github.com/upptime/upptime) により5分間隔で自動実行されています。"
  navbar:
    - title: Status
      href: /
    - title: pauth.me
      href: https://pauth.me
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
